nearform/titus

.github/workflows/backend-ci.yml, .github/workflows/db-manager-ci.yml, .github/workflows/frontend-ci.yml, renovate.json
and configure renovate to automerge without creating PRs (therefore silently) except for major bumps
=> chore: run ci on branches

packages/titus-backend/lib/plugins/auth/auth0/index.js, packages/titus-backend/lib/plugins/auth/azure-ad/index.js, packages/titus-backend/lib/plugins/auth/cognito/index.js, packages/titus-backend/lib/plugins/auth/index.js
because the index.js file conditionally registers them. Looks like something has changed in the behavior of fastify-autoload which recursively registers plugins in the plugins folder, whereas we don't want that for the authorization plugins, since its index.js entrypoint conditionally registers the auth plugin based on configuration.
This wasn't caught by automated tests possibly because no tests execute the whole server.
=> fix: avoid autoload on auth plugins in backend

docs/quick-start/README.md
Added the build criteria for fresh installs in the quick start docs.
Without that, the `mira` tests will fail.
=> fix(docs): added frontend build to quick-start

package-lock.json, package.json, renovate.json
Supersedes https://github.com/nearform/titus/pull/645/
Fixes #643 
Introduces two renovate options to prevent this from happening in the future:
- stability days which prevent bumping dependencies unless they've been released for at least 7 days
- pr creation which doesn't create PRs until the deps are ready to be updated (meaning that 7 days have elapsed)
Also, it limits lerna's concurrency when running lint:staged script to 1 as it breaks otherwise due to a lint-staged issue.
=> fix: rollback husky and prevent it from happening again

packages/titus-frontend/.storybook/main.js
This fixes storybook file imports being broken due to https://github.com/nearform/titus/pull/644
Adds a custom webpack alias for `.storybook` so that storybook config files can be imported absolutely in stories.
=> Create an alias for storybook

packages/titus-backend/package-lock.json, packages/titus-db-manager/package-lock.json, packages/titus-frontend/package-lock.json, packages/titus-frontend/package.json
closes #656 
`typescript`, `eslint-plugin-promise`, `eslint-plugin-import` are all required by the linter
`react-is` is the only peer dependancy, however its not imported in the code and not needed in the `package.json`
=> chore: remove unused packages

packages/titus-infra-aws-mira/pipeline/buildspec.sample.yaml
closes https://github.com/nearform/titus/issues/635
=> chore(deps): use node 14 lts for mira

docs/quick-start/README.md, lib/package.json
This PR intends to remark the importance of building the frontend before running the tests. 
Also it decorates the build commands for better readability .
It may be related to #636
=> Rewriting getting started commands for testing

lib/tools.js
Closes #851 
With this PR, the `create:env` and `clean:env` scripts will use each package's `location` property to look for or create corresponding `.env` / `.env.sample` files. This change makes it possible to have a package name that does not exactly equal the name of the package's containing directory.
Other minor updates include:
1. Improve logging messages.
2. Simplify code since we now have a path, rather than a name that needs to be concatenated into a path.
3. Minor 'improvements' based on developer preference.
Test Results:
=> Prefer package.location to package.name in (create/clean)Env fns

docs/devops/_sidebar.md, docs/devops/aws/README.md
The new documentation to deploy on AWS using terraform was not linked into the sidebar.
=> docs: link AWS page in sidebar

docs/devops/gcp/README.md, infra/gcp/terraform/main.tf
The code was already compatible with terraform 1.0.0, this PR just updates the documentation and sets a `required_version` statement as in the other `main.tf` files (for AWS and Azure)
Closes #933
=> updates code and docs to support terraform 1.0.0

infra/azure/terraform/backend.tf, infra/azure/terraform/db-manager.tf
Containerized apps in Azure now uses by default `azure` secrets strategy and the correct value for db password.
Closes #1004
=> Updates SECRETS_PG_PASS env value

packages/titus-backend/lib/config/index.js
Removes CORS_ORIGIN prop that was listed twice in the config
=> fix: remove duplicate prop

packages/titus-backend/index.js, packages/titus-backend/package.json
Inspired from how it's used in https://github.com/fastify/fastify-cli/blob/master/templates/eject/server.js
Closes #1137
=> feat: use close-with-grace for graceful server shutdown

docs/developers/packages/titus-db-manager/README.md, packages/titus-db-manager/index.js, packages/titus-db-manager/lib/routes.js, packages/titus-db-manager/lib/server.integration.test.js, packages/titus-db-manager/lib/server.test.js, packages/titus-db-manager/migrate/index.js, packages/titus-db-manager/migrate/index.test.js, packages/titus-db-manager/migration-start.js, packages/titus-db-manager/seed/index.js, packages/titus-db-manager/seed/index.test.js, packages/titus-db-manager/truncate/index.js, packages/titus-db-manager/truncate/index.test.js
=> add: configurable pg schema

packages/titus-frontend/.storybook/main.js
Fixes #1465 
This is just a temporary fix, to get the CI builds green again. The reason for the fails was the [deprecation of `addon-knobs`](https://github.com/storybookjs/storybook/discussions/15060), and apparently a bug introduced when it was being moved outside of the monorepo.
Storybook's API has been changing quite a lot within the last two major versions, and the current setup in titus could use a bit of an update (it actually no longer works when started locally).
=> chore: fix storybook deploy action

.github/workflows/backend-cd-gcp.yml, .github/workflows/db-manager-cd-gcp.yml, .github/workflows/frontend-cd-gcp.yml, .github/workflows/storybook-cd-gcp.yml
setup-gcloud will be updating the branch name from master to main in a future release. Even though GitHub will establish redirects, this will break any GitHub Actions workflows that pin to master. This PR updates your GitHub Actions workflows to pin to v0, which is the recommended best practice.
=> Pin setup-gcloud to v0 instead of master

.github/workflows/backend-cd-gcp.yml, infra/gcp/terraform/backend.tf, infra/gcp/terraform/config.auto.tfvars.sample, infra/gcp/terraform/db-manager.tf, infra/gcp/terraform/variables.tf
Since the deploy is failing due the missing required env `IS_PRODUCTION` I created an env and add a new parameter at the the deploy step to use the env
=> fix: detect production environment

.github/workflows/backend-cd-gcp.yml, .github/workflows/db-manager-cd-gcp.yml, .github/workflows/frontend-cd-gcp.yml, .github/workflows/storybook-cd-gcp.yml
Replaced deprecated way of GCP authentication along with instructions from [docs](https://github.com/google-github-actions/deploy-cloudrun#authenticating-via-service-account-key-json) and [docs](https://github.com/google-github-actions/setup-gcloud#authentication-inputs).
For warnings please see:
https://github.com/nearform/titus/actions/runs/2261365900
https://github.com/nearform/titus/actions/runs/2261365898
https://github.com/nearform/titus/actions/runs/2261365901
https://github.com/nearform/titus/actions/runs/2261365902
=> chore: replaced deprecated way of GCP authentication in cd workflow

.github/workflows/frontend-ci.yml
remove optional github token from frontend
=> chore: remove optional github token frontend
