packages/titus-backend/lib/routes/healthcheck/healthcheck.test.js, packages/titus-backend/lib/routes/healthcheck/index.js, packages/titus-backend/lib/routes/log/index.js, packages/titus-backend/lib/routes/log/log.test.js, packages/titus-backend/lib/routes/user/index.js, packages/titus-backend/lib/routes/user/user.test.js
Closes https://github.com/nearform/titus/issues/642
=> normalize routes

package-lock.json, package.json, packages/titus-frontend/.env.sample, packages/titus-frontend/.env.test, packages/titus-infra-aws-mira/package-lock.json
Closes https://github.com/nearform/titus/issues/713
=> fix(deps): use fixed Jest version that doesn't conflict with CRA

docs/devops/gcp/README.md, infra/gcp/terraform/backend.tf, infra/gcp/terraform/db-manager.tf, infra/gcp/terraform/iam.tf
Fixes #787 to be able to deploy on GCP without any manual changes.
=> GCP deploy fixes

docs/devops/gcp/README.md
This will probably require some more info on iam bindings
=> add gcloud commands for setup, more needed regarding iam bindings

docs/devops/README.md, docs/devops/gcp/_sidebar.md
Adding Azure missing part into the docs devops README file
=> Docs azure

packages/titus-backend/Dockerfile
Adjust the Dockerfile according to tips in this article:
https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/
Resolve #986
=> Align docker image for backend with current best practices

packages/titus-db-manager/.dockerignore, packages/titus-db-manager/Dockerfile
=> Enable running migrations from the docker container

packages/titus-db-manager/Dockerfile
- do the same thing as in #988
=> Align docker image for db-manager with the current best practices

.github/workflows/frontend-cd-gcp.yml, infra/gcp/terraform/.terraform.lock.hcl
add cp .env.sample .env to docker build task
=> add .env.sample copy ebfore build

infra/k8s/helm/templates/db-migrate-job.yaml, infra/k8s/helm/templates/deployment.yaml, infra/k8s/helm/values.yaml
This PR allows the user to set the value of the registry for all the images to be pulled from. By default this can be the nearform docker hub account. 
It also allows you to set the tag for db manager now
=> parse registry as value

packages/titus-backend/.gitlab-ci.yml, packages/titus-db-manager/.gitlab-ci.yml, packages/titus-frontend/.gitlab-ci.yml
Adding gitlab ci file for building 3 different containers and pushing to ecr
=> add gitlab ci for building containers

packages/titus-db-manager/lib/routes.js, packages/titus-db-manager/migration-start.js
- changes for upgrading postgrator
Now Postgrator config requires a`execQuery` property where to pass the db client instance.
https://github.com/rickbergfalk/postgrator
=> fix: postgrator upgrade

packages/titus-frontend/package-lock.json
Frontend package lock file has some references to localhost.
Restored that to point to https://registry.npmjs.org.
See issue #1453
=> Fix package refs to localhost

.github/workflows/backend-cd-gcp.yml, .github/workflows/db-manager-cd-gcp.yml, .github/workflows/frontend-cd-gcp.yml, .github/workflows/storybook-cd-gcp.yml
Fix Cloud Run service names in 3 workflows. It's now working:
- Frontend: https://github.com/nearform/titus/actions/runs/1654881689
- DB Manager: https://github.com/nearform/titus/actions/runs/1654881696
- Storybook: pending
=> Fix Cloud Run service names

infra/aws/terraform/backend.tf
Please, have a look at discussion at #1475.
=> Open traffic to HTTP port and remove wrong source IP

infra/aws/terraform/cdn.tf, infra/aws/terraform/storage.tf
Please read the discussion at #1474.
=> Connect CDN to correct S3 bucket & restrict access by using an OAI

packages/titus-backend-typescript/src/config/index.ts, packages/titus-backend/lib/config/index.js, packages/titus-db-manager/lib/config.js
=> fix: strictly check if NODE_ENV is 'production'

.github/dependabot.yml, .github/workflows/lib-ci.yml, lib/package-lock.json, lib/package.json, packages/titus-frontend/package-lock.json, packages/titus-frontend/package.json
Fixes #1487 
This came about when getting Titus to run locally.
I've pinned the dependency and removed it where it was not being used.
I've added a new CI action to ensure the titus-lib tests are run if the directory is modified.
=> fix: pin chalk dev dependency and run titus-lib test on CI

packages/titus-backend-typescript/.env.sample, packages/titus-backend-typescript/src/config/index.ts, packages/titus-backend/.env.sample, packages/titus-backend/lib/config/index.js, packages/titus-db-manager/.env.sample, packages/titus-db-manager/lib/config.js
Closes #1484 
add a new env variable to detect live env
=> fix: detect production environment

.github/workflows/backend-cd-gcp.yml
This fix #1517 and it's adding workflow_dispatch to have the ability to trigger the workflow from the UI
=> adding workflow_dispatch to have the ability to trigger the workflow from the UI

.github/workflows/db-manager-cd-gcp.yml, .github/workflows/frontend-cd-gcp.yml, .github/workflows/storybook-cd-gcp.yml
This fix #1518 this will add manual trigger at the cd workflows
=> adding workflow_dispatch to the cd workflows

.github/workflows/backend-ci.yml
=> chore: removed optional github token

README.md
As discussed at the TSR 17th July - action to add messaging to Titus saying it is now for reference only and no longer accepting PRs
Chore : titus going into reference mode  Resolves #1533
https://github.com/nearform/titus/issues/1533
=> Chore : titus going into reference mode https://github.com/nearform/titus/issues/1533
